### ISSUE TITLE
pEvent.iterator mishandles rejectionEvents

### ISSUE THREAD

**Issue by yoursunny** [sindresorhus/p-event#39] opened 2021-06-21 04:16 UTC
EventEmitter in this script emits two values followed by an error:

```js
const pEvent = require("p-event");
const { EventEmitter } = require("events");

const m = new EventEmitter();

(async () => {
  try {
    for await (const value of pEvent.iterator(m, "value", {
      resolutionEvents: ["end"],
      rejectionEvents: ["error"],
    })) {
      console.log(`value ${value}`);
    }
    console.log("end");
  } catch (err) {
    console.log(`error ${err}`);
  }
})();

void setTimeout(() => {
  m.emit("value", 1);
  m.emit("value", 2);
  m.emit("error", new Error("xxxx"));
}, 100);
```

I expect pEvent.iterator to yield two values, and then throw an error:

```text
value 1
value 2
error xxxx
```

However, as of v4.2.0, pEvent.iterator yields the first value, eats the second value, and then ends the iterator normally without throwing the error:

```text
value 1
end
```

**Comment by sindresorhus** [comment] 2021-06-23 14:00
Duplicate of #34

**Closed by sindresorhus** 2021-06-23 14:00 UTC

**Comment by sindresorhus** [comment] 2021-06-23 14:02
At least, I think it's the same case.

Does it work if you use the workaround in https://github.com/sindresorhus/p-event/issues/34#issuecomment-731884568 ?
